In [1]:
# Import packages

library(tidyverse)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.3     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.4     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.0
✔ purrr     1.0.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [2]:
# Enrollment data

# Month list for 2018
monthlist <- sprintf("%02d", 1:12)

# Readers ---------------------------------------------------------------
read_contract <- function(path) {
  read_csv(
    path,
    skip = 1,
    col_names = c(
      "contractid","planid","org_type","plan_type","partd","snp","eghp",
      "org_name","org_marketing_name","plan_name","parent_org","contract_date"
    ),
    col_types = cols(
      contractid = col_character(),
      planid = col_double(),
      org_type = col_character(),
      plan_type = col_character(),
      partd = col_character(),
      snp = col_character(),
      eghp = col_character(),
      org_name = col_character(),
      org_marketing_name = col_character(),
      plan_name = col_character(),
      parent_org = col_character(),
      contract_date = col_character()
    ),
    show_col_types = FALSE,
    progress = FALSE
  )
}

read_enroll <- function(path) {
  read_csv(
    path,
    skip = 1,
    col_names = c("contractid","planid","ssa","fips","state","county","enrollment"),
    col_types = cols(
      contractid = col_character(),
      planid = col_double(),
      ssa = col_double(),
      fips = col_double(),
      state = col_character(),
      county = col_character(),
      enrollment = col_double()
    ),
    na = "*",
    show_col_types = FALSE,
    progress = FALSE
  )
}

# One-month loader --------------------------------------------------------
load_month <- function(m) {
  y <- 2018
  c_path <- paste0("../ma-data/ma/enrollment/Extracted Data/CPSC_Contract_Info_", y, "_", m, ".csv")
  e_path <- paste0("../ma-data/ma/enrollment/Extracted Data/CPSC_Enrollment_Info_", y, "_", m, ".csv")
  
  contract.info <- read_contract(c_path) %>% distinct(contractid, planid, .keep_all = TRUE)
  enroll.info <- read_enroll(e_path)
  
  contract.info %>%
    left_join(enroll.info, by = c("contractid","planid")) %>%
    mutate(month = as.integer(m), year = y)
}

# Read all months and tidy -----------------------------------------------
plan.year <- map_dfr(monthlist, load_month) %>%
  arrange(contractid, planid, state, county, month) %>%
  group_by(state, county) %>% fill(fips, .direction = "downup") %>%
  ungroup() %>%
  group_by(contractid, planid) %>% fill(plan_type, partd, snp, eghp, plan_name, .direction = "downup")

Warning message:
“One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat)”
Warning message:
“One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat)”
Warning message:
“One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat)”
Warning message:
“One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat)”
Warning message:
“One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat)”
Warning message:
“One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat)”
Warning message:
“One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat)”
Warning message:
“One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat)”
Warning message:
“One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat)”
Warning message:
“One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat)”
Warning message:
“One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat)”
Warning message:
“One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat)”

In [3]:
# Check

head(plan.year)

  contractid planid org_type         plan_type        partd snp eghp
1 90091      NA     HCPP - 1833 Cost HCPP - 1833 Cost No    No  No
2 90091      NA     HCPP - 1833 Cost HCPP - 1833 Cost No    No  No
3 90091      NA     HCPP - 1833 Cost HCPP - 1833 Cost No    No  No
4 90091      NA     HCPP - 1833 Cost HCPP - 1833 Cost No    No  No
5 90091      NA     HCPP - 1833 Cost HCPP - 1833 Cost No    No  No
6 90091      NA     HCPP - 1833 Cost HCPP - 1833 Cost No    No  No
  org_name
1 UNITED MINE WORKERS OF AMERICA HLTH & RETIREMENT
2 UNITED MINE WORKERS OF AMERICA HLTH & RETIREMENT
3 UNITED MINE WORKERS OF AMERICA HLTH & RETIREMENT
4 UNITED MINE WORKERS OF AMERICA HLTH & RETIREMENT
5 UNITED MINE WORKERS OF AMERICA HLTH & RETIREMENT
6 UNITED MINE WORKERS OF AMERICA HLTH & RETIREMENT
  org_marketing_name                                 plan_name
1 United Mine Workers of America Health & Retirement NA
2 United Mine Workers of America Health & Retirement NA
3 United Mine Workers of America Health & Retirement NA
4 United Mine Workers of America Health & Retirement NA
5 United Mine Workers of America Health & Retirement NA
6 United Mine Workers of America Health & Retirement NA
  parent_org                       contract_date      ssa fips state county
1 UMWA Health and Retirement Funds 02/01/1974 0:00:00 NA  NA   NA    NA
2 UMWA Health and Retirement Funds 02/01/1974 0:00:00 NA  NA   NA    NA
3 UMWA Health and Retirement Funds 02/01/1974 0:00:00 NA  NA   NA    NA
4 UMWA Health and Retirement Funds 02/01/1974 0:00:00 NA  NA   NA    NA
5 UMWA Health and Retirement Funds 02/01/1974 0:00:00 NA  NA   NA    NA
6 UMWA Health and Retirement Funds 02/01/1974 0:00:00 NA  NA   NA    NA
  enrollment month year
1 NA         1     2018
2 NA         2     2018
3 NA         3     2018
4 NA         4     2018
5 NA         5     2018
6 NA         6     2018

In [4]:
# Create final table

yearly_plans <- plan.year %>%
  group_by(contractid, planid, fips, year) %>%
  summarize(
    plan_type = first(plan_type),
    snp = first(snp),
    eghp = first(eghp),
    avg_enrollment = mean(enrollment, na.rm = TRUE),
    .groups = "drop"
  )

In [5]:
# Check enrollment data

head(yearly_plans)

  contractid planid fips year plan_type                               snp eghp
1 90091       NA      NA 2018 HCPP - 1833 Cost                        No  No
2 E0654      801    1001 2018 Employer/Union Only Direct Contract PDP No  Yes
3 E0654      801    1003 2018 Employer/Union Only Direct Contract PDP No  Yes
4 E0654      801    1005 2018 Employer/Union Only Direct Contract PDP No  Yes
5 E0654      801    1007 2018 Employer/Union Only Direct Contract PDP No  Yes
6 E0654      801    1009 2018 Employer/Union Only Direct Contract PDP No  Yes
  avg_enrollment
1      NaN
2      NaN
3 13.83333
4      NaN
5      NaN
6      NaN

In [6]:
# Service area data

# Month list for 2018 ----------------------------------------------------
monthlist <- sprintf("%02d", 1:12)

# Reader ----------------------------------------------------------------
read_service_area <- function(path) {
  read_csv(
    path,
    skip = 1,
    col_names = c(
      "contractid","org_name","org_type","plan_type","partial","eghp",
      "ssa","fips","county","state","notes"
    ),
    col_types = cols(
      contractid = col_character(),
      org_name   = col_character(),
      org_type   = col_character(),
      plan_type  = col_character(),
      partial    = col_logical(),
      eghp       = col_character(),
      ssa        = col_double(),
      fips       = col_double(),
      county     = col_character(),
      state      = col_character(),
      notes      = col_character()
    ),
    na = "*",
    show_col_types = FALSE,
    progress = FALSE
  )
}

# One-month loader -------------------------------------------------------
load_month_sa <- function(m) {
  y <- 2018
  path <- paste0(
    "../ma-data/ma/service-area/Extracted Data/MA_Cnty_SA_",
    y, "_", m, ".csv"
  )
  
  read_service_area(path) %>%
    mutate(month = as.integer(m), year = y)
}

# Read all months --------------------------------------------------------
service.year <- map_dfr(monthlist, load_month_sa)

# Ensure stable order before fills --------------------------------------
service.year <- service.year %>%
  arrange(contractid, fips, state, county, month)

# Fill missing identifiers/labels ---------------------------------------
service.year <- service.year %>%
  group_by(state, county) %>%
  fill(fips, .direction = "downup") %>%
  ungroup() %>%
  group_by(contractid) %>%
  fill(plan_type, partial, eghp, org_type, org_name, .direction = "downup") %>%
  ungroup()

# Collapse to yearly: one row per contract × county × year ---------------
final.service.area <- service.year %>%
  group_by(contractid, fips, year) %>%
  summarize(
    state     = first(state),
    county    = first(county),
    org_name  = first(org_name),
    org_type  = first(org_type),
    plan_type = first(plan_type),
    partial   = first(partial),
    eghp      = first(eghp),
    ssa       = first(ssa),
    notes     = first(notes),
    .groups = "drop"
  )

Warning message:
“One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat)”
Warning message:
“One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat)”
Warning message:
“One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat)”
Warning message:
“One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat)”
Warning message:
“One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat)”
Warning message:
“One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat)”
Warning message:
“One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat)”
Warning message:
“One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat)”
Warning message:
“One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat)”
Warning message:
“One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat)”
Warning message:
“One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat)”
Warning message:
“One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat)”

In [7]:
# Check

head(final.service.area)
n_distinct(final.service.area$year)

  contractid fips  year state county
1 90091         NA 2018
2 H0022      39023 2018 OH    Clark
3 H0022      39035 2018 OH    Cuyahoga
4 H0022      39051 2018 OH    Fulton
5 H0022      39055 2018 OH    Geauga
6 H0022      39057 2018 OH    Greene
  org_name                                         org_type
1 UNITED MINE WORKERS OF AMERICA HLTH & RETIREMENT HCPP - 1833 Cost
2 BUCKEYE COMMUNITY HEALTH PLAN, INC.              Demo
3 BUCKEYE COMMUNITY HEALTH PLAN, INC.              Demo
4 BUCKEYE COMMUNITY HEALTH PLAN, INC.              Demo
5 BUCKEYE COMMUNITY HEALTH PLAN, INC.              Demo
6 BUCKEYE COMMUNITY HEALTH PLAN, INC.              Demo
  plan_type                         partial eghp ssa
1 HCPP - 1833 Cost                  NA              NA
2 Medicare-Medicaid Plan HMO/HMOPOS NA           36110
3 Medicare-Medicaid Plan HMO/HMOPOS NA           36170
4 Medicare-Medicaid Plan HMO/HMOPOS NA           36260
5 Medicare-Medicaid Plan HMO/HMOPOS NA           36280
6 Medicare-Medicaid Plan HMO/HMOPOS NA           36290
  notes
1 Covers the entire US, all States and Counties
2
3
4
5
6

[1] 1

In [8]:
# Drop NAs

yearly_plans <- yearly_plans %>%
  filter(!is.na(planid), !is.na(fips))

final.service.area <- final.service.area %>%
  filter(!is.na(fips))

In [9]:
# Inner merge

approved_plans <- yearly_plans %>%
  inner_join(
    final.service.area,
    by = c("contractid", "fips", "year")
  )

In [10]:
# Check merge

head(approved_plans)
nrow(yearly_plans)
nrow(approved_plans)

  contractid planid fips  year plan_type.x                       snp eghp.x
1 H0022      1      39023 2018 Medicare-Medicaid Plan HMO/HMOPOS No  No
2 H0022      1      39035 2018 Medicare-Medicaid Plan HMO/HMOPOS No  No
3 H0022      1      39051 2018 Medicare-Medicaid Plan HMO/HMOPOS No  No
4 H0022      1      39055 2018 Medicare-Medicaid Plan HMO/HMOPOS No  No
5 H0022      1      39057 2018 Medicare-Medicaid Plan HMO/HMOPOS No  No
6 H0022      1      39085 2018 Medicare-Medicaid Plan HMO/HMOPOS No  No
  avg_enrollment state county   org_name                            org_type
1  598.41667     OH    Clark    BUCKEYE COMMUNITY HEALTH PLAN, INC. Demo
2 3653.00000     OH    Cuyahoga BUCKEYE COMMUNITY HEALTH PLAN, INC. Demo
3  115.83333     OH    Fulton   BUCKEYE COMMUNITY HEALTH PLAN, INC. Demo
4   77.33333     OH    Geauga   BUCKEYE COMMUNITY HEALTH PLAN, INC. Demo
5  571.08333     OH    Greene   BUCKEYE COMMUNITY HEALTH PLAN, INC. Demo
6  303.16667     OH    Lake     BUCKEYE COMMUNITY HEALTH PLAN, INC. Demo
  plan_type.y                       partial eghp.y ssa   notes
1 Medicare-Medicaid Plan HMO/HMOPOS NA             36110
2 Medicare-Medicaid Plan HMO/HMOPOS NA             36170
3 Medicare-Medicaid Plan HMO/HMOPOS NA             36260
4 Medicare-Medicaid Plan HMO/HMOPOS NA             36280
5 Medicare-Medicaid Plan HMO/HMOPOS NA             36290
6 Medicare-Medicaid Plan HMO/HMOPOS NA             36440

[1] 2473062

[1] 1366487

In [30]:
# Question 1: Table 1

table1 <- yearly_plans %>%
  distinct(contractid, planid, plan_type) %>%
  count(plan_type, name = "Number of Plans") %>%
  arrange(plan_type) %>%
  rename(`Plan Type` = plan_type)

knitr::kable(
  table1,
  caption = "Count of Plans by Plan Type (2018)",
  format="simple"
)

Table: Count of Plans by Plan Type (2018)

Plan Type                                  Number of Plans
----------------------------------------  ----------------
1876 Cost                                              101
Employer/Union Only Direct Contract PDP                  3
HMO/HMOPOS                                            2678
Local PPO                                              966
MSA                                                      5
Medicare Prescription Drug Plan                       1011
Medicare-Medicaid Plan HMO/HMOPOS                       54
National PACE                                          258
PFFS                                                    50
Regional PPO                                           109

In [31]:
# Question 2: Updated Table 1 (Exclude SNP, eghp, and 800-series plans)

table1_updated <- yearly_plans %>%
  filter(
    snp != "Yes",
    eghp != "Yes",
    planid < 800
  ) %>%
  distinct(contractid, planid, plan_type) %>%
  count(plan_type, name = "Number of Plans") %>%
  arrange(plan_type) %>%
  rename(`Plan Type` = plan_type)

knitr::kable(
  table1_updated,
  caption = "Count of Plans by Plan Type (Excluding SNP, EGHP, and 800-Series Plans)",
  format="simple"
)

Table: Count of Plans by Plan Type (Excluding SNP, EGHP, and 800-Series Plans)

Plan Type                            Number of Plans
----------------------------------  ----------------
1876 Cost                                         89
HMO/HMOPOS                                      1569
Local PPO                                        569
MSA                                                3
Medicare Prescription Drug Plan                  794
Medicare-Medicaid Plan HMO/HMOPOS                 54
National PACE                                    258
PFFS                                              46
Regional PPO                                      49

In [29]:
# Question 3: Average enrollments, only  counties in which plans are approved as per the service area files

table_avg_enrollment <- approved_plans %>%
  filter(
    snp != "Yes",
    eghp.x != "Yes",
    planid < 800
  ) %>%
  group_by(plan_type.x) %>%
  summarize(
    avg_enrollment = round(mean(avg_enrollment, na.rm = TRUE)),
    .groups = "drop"
  ) %>%
  arrange(plan_type.x) %>%
  rename(
    `Plan Type` = plan_type.x,
    `Average Enrollment` = avg_enrollment
  )

knitr::kable(
  table_avg_enrollment,
  caption = "Average Enrollment by Plan Type (2018)",
format="simple"
)

Table: Average Enrollment by Plan Type (2018)

Plan Type                            Average Enrollment
----------------------------------  -------------------
1876 Cost                                           253
HMO/HMOPOS                                          756
Local PPO                                           331
MSA                                                  58
Medicare-Medicaid Plan HMO/HMOPOS                   989
National PACE                                       144
PFFS                                                 94
Regional PPO                                        189